### ISSUE TITLE
Lab 04 Self service counter are not unable to generate served event at the right time

### ISSUE THREAD

**Issue by Zhou-Shude** [nus-cs2030/2324-s1#57] opened 2023-10-24 03:44 UTC
The self-service counter is unable to generate a serve event right after the done event of the self-service server.

In my implementation, the self-service server is a child class of human server with its own overrided method.
Self-service servers are in the same server list with the human server and the 1st self-service will take care of the wait event of all the self-service server ( 1st self-service server having Q max while the rest has q max as zero). The wait event will take in the fastest server time from all self-service server and decides if the customer get served or continue waiting at the k+1 server using the fastest server's time.

When I upload the code to code crunch, 
Following error appeared: 
![image](https://github.com/nus-cs2030/2324-s1/assets/146441325/d7f7f864-b1e9-496d-8155-f20c6f949ebe)
![image](https://github.com/nus-cs2030/2324-s1/assets/146441325/5d4ad16d-9b0f-46ca-ad93-4dfc722ef854)

However, when I attempt to test the code using randomly generated arrival time to see if the served event is generated at the right time, it seems to be generating the served event at the correct time.

![image](https://github.com/nus-cs2030/2324-s1/assets/146441325/7e349061-12f9-43db-b86a-e8940556fbc2)

The code for this part is as followed:

![image](https://github.com/nus-cs2030/2324-s1/assets/146441325/f2a1b7d9-bb51-4a0e-b3b7-65ec21b03f5c)

**Comment by somethingfishyfishy** [comment] 2023-10-24 12:40
Quite sure this is test case 9_11. Some of my friends encountered the same error output.

This means that Customer 13 was supposed to be assigned to self-check 4, but was assigned to self-check 3 instead. Meaning when Customer 13 was in the waiting queue, it was not assigned to the earliest self-check available, it was just assigned to the queue it was waiting at.

So the is how it is supposed to look like
`0.862 9 done serving by self-check 4 
_0.862 13 was waiting at self-check 3 [update event for 13 to Serve(cust13, self-check 4)]_
0.862 13 serves by self-check 4 _[update to Done(cust13)]_
_0.862 14 was waiting at self-check 3 [update event for 14 to Wait(cust14, self-check 3)]_
1.050 15 arrives _[update event for 15 to Wait(cust15, self-check 3)]_
1.050 15 waits at self-check 3 _[update to XXX]_`

_Italicised means it is not printed_

Your current output does not have 13 is waiting at self-check 3 @ 0.862 (meaning that it is not checking for the earliest available server)

There are other ways to do this logic of finding the earliest available Self-Check (such as checking for completed Done Events by Self-Check counters)

Hope this answers. Good luck.

P.S.
> However, when I attempt to test the code using randomly generated arrival time to see if the served event is generated at the right time, it seems to be generating the served event at the correct time.

The issue that your code is facing is not the inability to handle random start times. The issue is the Waiting logic for your self-check counters. Hence when you are testing against the public cases (which doesn't test Waiting logic), you won't be able to tell that your Waiting logic is flawed.

**Comment by Zhou-Shude** [comment] 2023-10-24 18:57
> The issue that your code is facing is not the inability to handle random start times. The issue is the Waiting logic for your self-check counters. Hence when you are testing against the public cases (which doesn't test Waiting logic), you won't be able to tell that your Waiting logic is flawed.

Hi, Instead of testing the code for random arriving time, I was actually testing if the served event can be generated after the done event. I randomized it so that there can be multiple occurrence of served event at the self check out counter can be generated after the done event at the self check out counter.



> ![image](https://user-images.githubusercontent.com/146441325/277542494-7e349061-12f9-43db-b86a-e8940556fbc2.png)

If you look here, you will see that 9 and 10 which initially waits at self check up counter 3 gets served immediated after the done event at self check up 3 and 4.
I did a multiple set of such test case and they show that the wait event is somehow working.
Thats why im not sure why the code failed at the 9_11.

**Comment by ChinSekYi** [comment] 2023-10-29 04:32
I assume that your code above is from ContinueWaitingEvent.java? 

For now, I don't see any major problem with your code in the screenshot. 
I can see that you are searching for available servers/counters in the for loop, and then minusing a queue from the server.

Perhaps your problem arises from the issues below:
-  You minus the queue from the server before creating the Serve event. Perhaps you can consider minusing the queue only when the Serve event is executed. 

-  When you requeue the ContinueWaiting event in pq, did you update with the servers availableTime?

- Did your Done Event update the server's availableTime correctly?

If you can share more about yr implementation, i'll try to help you further.

**Comment by shude1999** [comment] 2023-10-29 06:07
> I assume that your code above is from ContinueWaitingEvent.java?
yes, it is the ContinueWaiting event.
> Perhaps your problem arises from the issues below:
> * You minus the queue from the server before creating the Serve event. Perhaps you can consider minusing the queue only when the Serve event is executed.
The queue is intended to be minus here as not all customer served in served event are from the waiting queue.
if a customer gets served == he is no longer tin the queue

> * When you requeue the ContinueWaiting event in pq, did you update with the servers availableTime?
yes, when requeuing the continuewaiting event, the time it set to be the time of self-check out server that is going to be done soon
> * Did your Done Event update the server's availableTime correctly?
Yes. it did

> If you can share more about yr implementation, i'll try to help you further.
This is the only part that affects the result of the served Event generation.
I realize that somehow the soonServer used to generate the served event refers to the server that the customer is queued at instead of the soonServer for the test case 9_11 which shouldnt be the case.
when I use testcases to forced there to be wait event at self check out counter, the reference of soonServer is correct and generate a serve event at the correct self check out server, so im acutally quite confuse with what is happening with the test cast 9_11

**Comment by shude1999** [comment] 2023-10-29 06:24
2 2 2 0.5
0.000000
0.313508
1.204910
2.776499
3.876961
3.909737
4.0
4.1
4.2
4.21
4.2
4.3
4.36
5.0
5.1
5.2
5.3
5.4
9.006391
9.043361
9.105379
9.159630

Hi, can you try running this test case and we compare output?

**Comment by ChinSekYi** [comment] 2023-10-29 06:31
Here is my output:
[output1.txt](https://github.com/nus-cs2030/2324-s1/files/13197349/output1.txt)

**Comment by shude1999** [comment] 2023-10-29 07:17
> Here is my output: [output1.txt](https://github.com/nus-cs2030/2324-s1/files/13197349/output1.txt)

Our output for this test case is the same

**Comment by ChinSekYi** [comment] 2023-10-29 09:53
Hmm, your code in the screenshot doesn't seem to have any problems.

But it seems like this.fastestServer() is not returning you the earliest available time for the self-checkout counters. I suspect that the serverlist is not updated correctly somewhere else, eg. in other events.  Might have to check your other event files because your code above might not necessarily be the source of error. 

Not sure if it'll be helpful, but I generated another test case here.
[in7.txt](https://github.com/nus-cs2030/2324-s1/files/13197735/in7.txt)
[output7.txt](https://github.com/nus-cs2030/2324-s1/files/13197734/output7.txt)

**Comment by shude1999** [comment] 2023-10-31 18:02
> Not sure if it'll be helpful, but I generated another test case here. [in7.txt](https://github.com/nus-cs2030/2324-s1/files/13197735/in7.txt) [output7.txt](https://github.com/nus-cs2030/2324-s1/files/13197734/output7.txt)

Thanks, your test case helped a lot! I manage to troubleshoot as it highlighted a mistake for me

**Closed** 2023-10-31 18:06 UTC

**Comment by ChinSekYi** [comment] 2023-10-31 18:34
Nice! 
dym sharing the mistake you found? I'm curious haha

**Comment by Zhou-Shude** [comment] 2023-10-31 18:45
> Nice! dym sharing the mistake you found? I'm curious haha


The time i used to generate continue waiting event is wrong.
At server Time T, my wait event will print out a string and generate a continue waiting event at time T. 

So for lab 1 to 3, server time T is equal to event time g.
However for lab 4, all my self check out server generated a queue at the 1st machine server, so they generate the continue waiting event at T instead of actual event time g.
So becomes xxx continue waiting at time T instead of time g.
I assumed it was right initially as all the test case i randomly generated has g>T which will show a right output. I'm not sure to consider myself as lucky/ unlucky for this
And the test case u generated somehow had g<T which allows me to troubleshoot.

**Comment by somethingfishyfishy** [comment] 2023-10-31 18:54
literally told you there was a problem with your waiting logic. 

Perhaps not specifically in the exact case I suspected, but there are probably linked steps since you mentioned that before you send to a Serve Event, you had a ContinueWaiting Event
